#:kivy 1.11.1

#:import translator translator.translator

<ArticlesMenuScreen>:
    name: 'articlesmenu'
    BoxLayout:
        orientation: 'vertical'
        padding: '4dp'
        canvas:
            Color:
                rgba: 1, 1, 1, 1
            Rectangle:
                pos: self.pos
                size: self.size
        ScreenTitleBar:
            title: translator.translate('Articles', translator.active_lang_code)
        ScrollView:
            id: articlesmenu_container
