#:kivy 1.11.1

<ArticlesScreen>:
    name: 'articles'
    BoxLayout:
        orientation: 'vertical'
        padding: '4dp'
        canvas:
            Color:
                rgba: 1, 1, 1, 1
            Rectangle:
                pos: self.pos
                size: self.size
        TitleBar:
            title: 'Articles'
        ScrollView:
            ArticlesMenu:
                data: root.articles_menu_items
