#:kivy 1.11.1

<ArticlesMenuScreen>:
    name: 'articlesmenu'
    screen_title: 'Articles'
    BoxLayout:
        orientation: 'vertical'
        padding: '4dp'
        canvas:
            Color:
                rgba: 1, 1, 1, 1
            Rectangle:
                pos: self.pos
                size: self.size
        ScreenTitleBar:
            title: root.screen_title
        ScrollView:
            id: articlesmenu_container
